androidx-media3-exoplayer-ffmpeg = { module = "androidx.media3:media3-exoplayer-ffmpeg", version.ref = "media3" }
androidx-media3-ui-compose = { module = "androidx.media3:media3-ui-compose", version.ref = "media3" }
    